/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.CraftStoreInventorySystem.view;

import java.awt.Color;
import javax.swing.ImageIcon;
/**
 *
 * @author A-Byte Wizards, DCCO - ESPE
 */
public final class FrmUniversoDelFomix extends javax.swing.JFrame {

    int xMouse, yMouse;
    
    public FrmUniversoDelFomix() {
        initComponents();
        hideStartBtnsMenu();
        setIconImage(new ImageIcon(getClass().getResource("/logo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void hideStartBtnsMenu(){
        AddProductBtn.setVisible(false);
        AddProductBtnTxt.setVisible(false);
        DeleteProductBtn.setVisible(false);
        DeleteProductBtnTxt.setVisible(false);
        EditProductBtn.setVisible(false);
        EditProductBtnTxt.setVisible(false);
        ViewInventoryBtn.setVisible(false);
        ViewInventoryBtnTxt.setVisible(false);
    }
    
    
    public void bgEntered(){
        mnuPanel.setBackground(new Color(110, 80, 159));
        mnuPanel1.setBackground(new Color(110, 80, 159));
        mnuPanel2.setBackground(new Color(110, 80, 159));
        LogOutBtn.setBackground(new Color(110, 80, 159));
        InventoryBtn.setBackground(new Color(110, 80, 159));
        StartBtn.setBackground(new Color(110, 80, 159));
    }
    public void bgExited(){
        mnuPanel.setBackground(new Color(110, 37, 159));
        mnuPanel1.setBackground(new Color(110, 37, 159));
        mnuPanel2.setBackground(new Color(110, 37, 159));
        LogOutBtn.setBackground(new Color(110, 37, 159));
        InventoryBtn.setBackground(new Color(110, 37, 159));
        StartBtn.setBackground(new Color(110, 37, 159));
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        mnuPanel2 = new javax.swing.JPanel();
        AddProductBtn = new javax.swing.JPanel();
        AddProductBtnTxt = new javax.swing.JLabel();
        DeleteProductBtn = new javax.swing.JPanel();
        DeleteProductBtnTxt = new javax.swing.JLabel();
        EditProductBtn = new javax.swing.JPanel();
        EditProductBtnTxt = new javax.swing.JLabel();
        ViewInventoryBtn = new javax.swing.JPanel();
        ViewInventoryBtnTxt = new javax.swing.JLabel();
        mnuPanel1 = new javax.swing.JPanel();
        LogOutBtn = new javax.swing.JPanel();
        LogOutBtnTxt = new javax.swing.JLabel();
        mnuPanel = new javax.swing.JPanel();
        StartBtn = new javax.swing.JPanel();
        StartBtnTxt = new javax.swing.JLabel();
        InventoryBtn = new javax.swing.JPanel();
        InventoryBtnTxt = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setUndecorated(true);
        setResizable(false);

        bgPanel.setBackground(new java.awt.Color(255, 255, 255));
        bgPanel.setMaximumSize(new java.awt.Dimension(800, 500));
        bgPanel.setPreferredSize(new java.awt.Dimension(800, 500));
        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mnuPanel2.setBackground(new java.awt.Color(110, 37, 159));
        mnuPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnuPanel2MouseExited(evt);
            }
        });

        AddProductBtn.setBackground(new java.awt.Color(110, 37, 159));

        AddProductBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        AddProductBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        AddProductBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddProductBtnTxt.setText("Añadir Producto");
        AddProductBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AddProductBtnTxt.setMaximumSize(new java.awt.Dimension(38, 19));
        AddProductBtnTxt.setMinimumSize(new java.awt.Dimension(38, 19));
        AddProductBtnTxt.setPreferredSize(new java.awt.Dimension(38, 19));
        AddProductBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddProductBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddProductBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddProductBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout AddProductBtnLayout = new javax.swing.GroupLayout(AddProductBtn);
        AddProductBtn.setLayout(AddProductBtnLayout);
        AddProductBtnLayout.setHorizontalGroup(
            AddProductBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
            .addGroup(AddProductBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AddProductBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AddProductBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        AddProductBtnLayout.setVerticalGroup(
            AddProductBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
            .addGroup(AddProductBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AddProductBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(AddProductBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        DeleteProductBtn.setBackground(new java.awt.Color(110, 37, 159));

        DeleteProductBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        DeleteProductBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        DeleteProductBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DeleteProductBtnTxt.setText("Eliminar Producto");
        DeleteProductBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DeleteProductBtnTxt.setMaximumSize(new java.awt.Dimension(38, 19));
        DeleteProductBtnTxt.setMinimumSize(new java.awt.Dimension(38, 19));
        DeleteProductBtnTxt.setPreferredSize(new java.awt.Dimension(38, 19));
        DeleteProductBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteProductBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteProductBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteProductBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout DeleteProductBtnLayout = new javax.swing.GroupLayout(DeleteProductBtn);
        DeleteProductBtn.setLayout(DeleteProductBtnLayout);
        DeleteProductBtnLayout.setHorizontalGroup(
            DeleteProductBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
            .addGroup(DeleteProductBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DeleteProductBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(DeleteProductBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        DeleteProductBtnLayout.setVerticalGroup(
            DeleteProductBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
            .addGroup(DeleteProductBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DeleteProductBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(DeleteProductBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        EditProductBtn.setBackground(new java.awt.Color(110, 37, 159));

        EditProductBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        EditProductBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        EditProductBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EditProductBtnTxt.setText("Editar Producto");
        EditProductBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        EditProductBtnTxt.setMaximumSize(new java.awt.Dimension(38, 19));
        EditProductBtnTxt.setMinimumSize(new java.awt.Dimension(38, 19));
        EditProductBtnTxt.setPreferredSize(new java.awt.Dimension(38, 19));
        EditProductBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditProductBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditProductBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditProductBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout EditProductBtnLayout = new javax.swing.GroupLayout(EditProductBtn);
        EditProductBtn.setLayout(EditProductBtnLayout);
        EditProductBtnLayout.setHorizontalGroup(
            EditProductBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
            .addGroup(EditProductBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EditProductBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(EditProductBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        EditProductBtnLayout.setVerticalGroup(
            EditProductBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
            .addGroup(EditProductBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EditProductBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(EditProductBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        ViewInventoryBtn.setBackground(new java.awt.Color(110, 37, 159));

        ViewInventoryBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        ViewInventoryBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        ViewInventoryBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ViewInventoryBtnTxt.setText("Ver Inventario");
        ViewInventoryBtnTxt.setAutoscrolls(true);
        ViewInventoryBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ViewInventoryBtnTxt.setMaximumSize(new java.awt.Dimension(38, 19));
        ViewInventoryBtnTxt.setMinimumSize(new java.awt.Dimension(38, 19));
        ViewInventoryBtnTxt.setPreferredSize(new java.awt.Dimension(38, 19));
        ViewInventoryBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewInventoryBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewInventoryBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewInventoryBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ViewInventoryBtnLayout = new javax.swing.GroupLayout(ViewInventoryBtn);
        ViewInventoryBtn.setLayout(ViewInventoryBtnLayout);
        ViewInventoryBtnLayout.setHorizontalGroup(
            ViewInventoryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
            .addGroup(ViewInventoryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ViewInventoryBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ViewInventoryBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ViewInventoryBtnLayout.setVerticalGroup(
            ViewInventoryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
            .addGroup(ViewInventoryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ViewInventoryBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ViewInventoryBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout mnuPanel2Layout = new javax.swing.GroupLayout(mnuPanel2);
        mnuPanel2.setLayout(mnuPanel2Layout);
        mnuPanel2Layout.setHorizontalGroup(
            mnuPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mnuPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(mnuPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnuPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(DeleteProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mnuPanel2Layout.createSequentialGroup()
                        .addGroup(mnuPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewInventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        mnuPanel2Layout.setVerticalGroup(
            mnuPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mnuPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(ViewInventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(AddProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(DeleteProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(EditProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bgPanel.add(mnuPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 160, 220));

        mnuPanel1.setBackground(new java.awt.Color(110, 37, 159));
        mnuPanel1.setPreferredSize(new java.awt.Dimension(165, 500));

        LogOutBtn.setBackground(new java.awt.Color(110, 37, 159));

        LogOutBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        LogOutBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        LogOutBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogOutBtnTxt.setText("Cerrar sesión");
        LogOutBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LogOutBtnTxt.setMaximumSize(new java.awt.Dimension(38, 19));
        LogOutBtnTxt.setMinimumSize(new java.awt.Dimension(38, 19));
        LogOutBtnTxt.setPreferredSize(new java.awt.Dimension(38, 19));
        LogOutBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogOutBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogOutBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout LogOutBtnLayout = new javax.swing.GroupLayout(LogOutBtn);
        LogOutBtn.setLayout(LogOutBtnLayout);
        LogOutBtnLayout.setHorizontalGroup(
            LogOutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
            .addGroup(LogOutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(LogOutBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
        );
        LogOutBtnLayout.setVerticalGroup(
            LogOutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(LogOutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LogOutBtnLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(LogOutBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout mnuPanel1Layout = new javax.swing.GroupLayout(mnuPanel1);
        mnuPanel1.setLayout(mnuPanel1Layout);
        mnuPanel1Layout.setHorizontalGroup(
            mnuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mnuPanel1Layout.createSequentialGroup()
                .addComponent(LogOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        mnuPanel1Layout.setVerticalGroup(
            mnuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mnuPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(LogOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        bgPanel.add(mnuPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 160, 100));

        mnuPanel.setBackground(new java.awt.Color(110, 37, 159));
        mnuPanel.setPreferredSize(new java.awt.Dimension(165, 500));

        StartBtn.setBackground(new java.awt.Color(110, 37, 159));
        StartBtn.setPreferredSize(new java.awt.Dimension(160, 45));
        StartBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StartBtnMouseClicked(evt);
            }
        });

        StartBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        StartBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        StartBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StartBtnTxt.setText("Inicio");
        StartBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        StartBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StartBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StartBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StartBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout StartBtnLayout = new javax.swing.GroupLayout(StartBtn);
        StartBtn.setLayout(StartBtnLayout);
        StartBtnLayout.setHorizontalGroup(
            StartBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
            .addGroup(StartBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(StartBtnTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
        );
        StartBtnLayout.setVerticalGroup(
            StartBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
            .addGroup(StartBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(StartBtnTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
        );

        InventoryBtn.setBackground(new java.awt.Color(110, 37, 159));

        InventoryBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        InventoryBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        InventoryBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InventoryBtnTxt.setText("Inventario");
        InventoryBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        InventoryBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventoryBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InventoryBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InventoryBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout InventoryBtnLayout = new javax.swing.GroupLayout(InventoryBtn);
        InventoryBtn.setLayout(InventoryBtnLayout);
        InventoryBtnLayout.setHorizontalGroup(
            InventoryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
            .addGroup(InventoryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(InventoryBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
        );
        InventoryBtnLayout.setVerticalGroup(
            InventoryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
            .addGroup(InventoryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(InventoryBtnTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mnuPanelLayout = new javax.swing.GroupLayout(mnuPanel);
        mnuPanel.setLayout(mnuPanelLayout);
        mnuPanelLayout.setHorizontalGroup(
            mnuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mnuPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(mnuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mnuPanelLayout.setVerticalGroup(
            mnuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mnuPanelLayout.createSequentialGroup()
                .addComponent(StartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(InventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bgPanel.add(mnuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 190));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setPreferredSize(new java.awt.Dimension(800, 40));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap(760, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bgPanel.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 48)); // NOI18N
        jLabel1.setText("UNIVERSO DEL FOMIX");
        bgPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 530, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartBtnTxtMouseClicked
       FrmUniversoDelFomix frmUniversoDelFomix = new FrmUniversoDelFomix();
       this.setVisible(false);
       frmUniversoDelFomix.setVisible(true);    
    }//GEN-LAST:event_StartBtnTxtMouseClicked

    private void StartBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartBtnTxtMouseEntered
        StartBtn.setBackground(new Color(110, 80, 159));
        bgEntered();
    }//GEN-LAST:event_StartBtnTxtMouseEntered

    private void StartBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartBtnTxtMouseExited
        StartBtn.setBackground(new Color(110,37,159));
        bgExited();
    }//GEN-LAST:event_StartBtnTxtMouseExited

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void InventoryBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryBtnTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_InventoryBtnTxtMouseClicked

    private void InventoryBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryBtnTxtMouseEntered
        bgEntered();
        AddProductBtn.setVisible(true);
        AddProductBtnTxt.setVisible(true);
        EditProductBtn.setVisible(true);
        EditProductBtnTxt.setVisible(true);
        DeleteProductBtn.setVisible(true);
        DeleteProductBtnTxt.setVisible(true);
        ViewInventoryBtn.setVisible(true);
        ViewInventoryBtnTxt.setVisible(true);
    }//GEN-LAST:event_InventoryBtnTxtMouseEntered

    private void InventoryBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryBtnTxtMouseExited
        bgExited();
        AddProductBtn.setVisible(false);
        AddProductBtnTxt.setVisible(false);
        EditProductBtn.setVisible(false);
        EditProductBtnTxt.setVisible(false);
        DeleteProductBtn.setVisible(false);
        DeleteProductBtnTxt.setVisible(false);
        ViewInventoryBtn.setVisible(false);
        ViewInventoryBtnTxt.setVisible(false);
    }//GEN-LAST:event_InventoryBtnTxtMouseExited

    private void StartBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartBtnMouseClicked
        FrmUniversoDelFomixSplash frmUniversoDelFomixSplash = new FrmUniversoDelFomixSplash();
        this.setVisible(false);
        frmUniversoDelFomixSplash.setVisible(true);
    }//GEN-LAST:event_StartBtnMouseClicked

    private void ViewInventoryBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewInventoryBtnTxtMouseClicked
        FrmViewInventory frmViewInventory = new FrmViewInventory();
        this.setVisible(false);
        frmViewInventory.setVisible(true);
    }//GEN-LAST:event_ViewInventoryBtnTxtMouseClicked

    private void ViewInventoryBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewInventoryBtnTxtMouseEntered
        bgEntered();
        AddProductBtn.setVisible(true);
        AddProductBtnTxt.setVisible(true);
        EditProductBtn.setVisible(true);
        EditProductBtnTxt.setVisible(true);
        DeleteProductBtn.setVisible(true);
        DeleteProductBtnTxt.setVisible(true);
        ViewInventoryBtn.setVisible(true);
        ViewInventoryBtnTxt.setVisible(true);
    }//GEN-LAST:event_ViewInventoryBtnTxtMouseEntered

    private void ViewInventoryBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewInventoryBtnTxtMouseExited
        bgExited();
        AddProductBtn.setVisible(false);
        AddProductBtnTxt.setVisible(false);
        EditProductBtn.setVisible(false);
        EditProductBtnTxt.setVisible(false);
        DeleteProductBtn.setVisible(false);
        DeleteProductBtnTxt.setVisible(false);
        ViewInventoryBtn.setVisible(false);
        ViewInventoryBtnTxt.setVisible(false);
    }//GEN-LAST:event_ViewInventoryBtnTxtMouseExited

    private void AddProductBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddProductBtnTxtMouseClicked
        FrmAddProduct frmAddProduct = new FrmAddProduct();
        this.setVisible(false);
        frmAddProduct.setVisible(true);
    }//GEN-LAST:event_AddProductBtnTxtMouseClicked

    private void AddProductBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddProductBtnTxtMouseEntered
        bgEntered();
        AddProductBtn.setVisible(true);
        AddProductBtnTxt.setVisible(true);
        EditProductBtn.setVisible(true);
        EditProductBtnTxt.setVisible(true);
        DeleteProductBtn.setVisible(true);
        DeleteProductBtnTxt.setVisible(true);
        ViewInventoryBtn.setVisible(true);
        ViewInventoryBtnTxt.setVisible(true);
    }//GEN-LAST:event_AddProductBtnTxtMouseEntered

    private void AddProductBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddProductBtnTxtMouseExited
        bgExited();
        AddProductBtn.setVisible(false);
        AddProductBtnTxt.setVisible(false);
        EditProductBtn.setVisible(false);
        EditProductBtnTxt.setVisible(false);
        DeleteProductBtn.setVisible(false);
        DeleteProductBtnTxt.setVisible(false);
        ViewInventoryBtn.setVisible(false);
        ViewInventoryBtnTxt.setVisible(false);
    }//GEN-LAST:event_AddProductBtnTxtMouseExited

    private void DeleteProductBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteProductBtnTxtMouseClicked
        FrmDeleteProduct frmDeleteProduct = new FrmDeleteProduct();
        this.setVisible(false);
        frmDeleteProduct.setVisible(true);
    }//GEN-LAST:event_DeleteProductBtnTxtMouseClicked

    private void DeleteProductBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteProductBtnTxtMouseEntered
        bgEntered();
        AddProductBtn.setVisible(true);
        AddProductBtnTxt.setVisible(true);
        EditProductBtn.setVisible(true);
        EditProductBtnTxt.setVisible(true);
        DeleteProductBtn.setVisible(true);
        DeleteProductBtnTxt.setVisible(true);
        ViewInventoryBtn.setVisible(true);
        ViewInventoryBtnTxt.setVisible(true);
    }//GEN-LAST:event_DeleteProductBtnTxtMouseEntered

    private void DeleteProductBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteProductBtnTxtMouseExited
        bgExited();
        AddProductBtn.setVisible(false);
        AddProductBtnTxt.setVisible(false);
        EditProductBtn.setVisible(false);
        EditProductBtnTxt.setVisible(false);
        DeleteProductBtn.setVisible(false);
        DeleteProductBtnTxt.setVisible(false);
        ViewInventoryBtn.setVisible(false);
        ViewInventoryBtnTxt.setVisible(false);
    }//GEN-LAST:event_DeleteProductBtnTxtMouseExited

    private void EditProductBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditProductBtnTxtMouseClicked
        FrmEditProduct frmEditProduct = new FrmEditProduct();
        this.setVisible(false);
        frmEditProduct.setVisible(true);
    }//GEN-LAST:event_EditProductBtnTxtMouseClicked

    private void EditProductBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditProductBtnTxtMouseEntered
        bgEntered();
        AddProductBtn.setVisible(true);
        AddProductBtnTxt.setVisible(true);
        EditProductBtn.setVisible(true);
        EditProductBtnTxt.setVisible(true);
        DeleteProductBtn.setVisible(true);
        DeleteProductBtnTxt.setVisible(true);
        ViewInventoryBtn.setVisible(true);
        ViewInventoryBtnTxt.setVisible(true);
    }//GEN-LAST:event_EditProductBtnTxtMouseEntered

    private void EditProductBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditProductBtnTxtMouseExited
        bgExited();
        AddProductBtn.setVisible(false);
        AddProductBtnTxt.setVisible(false);
        EditProductBtn.setVisible(false);
        EditProductBtnTxt.setVisible(false);
        DeleteProductBtn.setVisible(false);
        DeleteProductBtnTxt.setVisible(false);
        ViewInventoryBtn.setVisible(false);
        ViewInventoryBtnTxt.setVisible(false);
        
    }//GEN-LAST:event_EditProductBtnTxtMouseExited

    private void mnuPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuPanel2MouseExited
        bgExited();
        AddProductBtn.setVisible(false);
        AddProductBtnTxt.setVisible(false);
        EditProductBtn.setVisible(false);
        EditProductBtnTxt.setVisible(false);
        DeleteProductBtn.setVisible(false);
        DeleteProductBtnTxt.setVisible(false);
        ViewInventoryBtn.setVisible(false);
        ViewInventoryBtnTxt.setVisible(false);
    }//GEN-LAST:event_mnuPanel2MouseExited

    private void mnuPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuPanel2MouseEntered
        bgEntered();
        AddProductBtn.setVisible(true);
        AddProductBtnTxt.setVisible(true);
        EditProductBtn.setVisible(true);
        EditProductBtnTxt.setVisible(true);
        DeleteProductBtn.setVisible(true);
        DeleteProductBtnTxt.setVisible(true);
        ViewInventoryBtn.setVisible(true);
        ViewInventoryBtnTxt.setVisible(true);
    }//GEN-LAST:event_mnuPanel2MouseEntered

    private void LogOutBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutBtnTxtMouseExited
        LogOutBtn.setBackground(new Color(110, 37, 159));
    }//GEN-LAST:event_LogOutBtnTxtMouseExited

    private void LogOutBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutBtnTxtMouseEntered
        LogOutBtn.setBackground(new Color(110, 80, 159));
    }//GEN-LAST:event_LogOutBtnTxtMouseEntered

    private void LogOutBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutBtnTxtMouseClicked
        FrmLogin frmLogin = new FrmLogin();
        this.setVisible(false);
        frmLogin.setVisible(true);
    }//GEN-LAST:event_LogOutBtnTxtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUniversoDelFomix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUniversoDelFomix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUniversoDelFomix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUniversoDelFomix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUniversoDelFomix().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddProductBtn;
    private javax.swing.JLabel AddProductBtnTxt;
    private javax.swing.JPanel DeleteProductBtn;
    private javax.swing.JLabel DeleteProductBtnTxt;
    private javax.swing.JPanel EditProductBtn;
    private javax.swing.JLabel EditProductBtnTxt;
    private javax.swing.JPanel InventoryBtn;
    private javax.swing.JLabel InventoryBtnTxt;
    private javax.swing.JPanel LogOutBtn;
    private javax.swing.JLabel LogOutBtnTxt;
    private javax.swing.JPanel StartBtn;
    private javax.swing.JLabel StartBtnTxt;
    private javax.swing.JPanel ViewInventoryBtn;
    private javax.swing.JLabel ViewInventoryBtnTxt;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mnuPanel;
    private javax.swing.JPanel mnuPanel1;
    private javax.swing.JPanel mnuPanel2;
    // End of variables declaration//GEN-END:variables
}
